Repository Kapoor-0905/Hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#6 Create GuessTheNumber.py
  Python codes/GuessTheNumber.py
Labels: Hactoberfest-Accepted, Game

#7 Student Grade System
  student grades/Student Grading System.py
Labels: Hactoberfest-Accepted

#9 Banking System
  Python codes/BankingSystem.py
Labels: Hacktoberfest-Accepted

#11 billing system
  Bill Management System in Python/app.py
Labels: Hacktoberfest-Accepted, Hacktoberfest

#12 Minecraft Game - Python
  Minecraft-in-Python-main/Minecraft-in-Python-main/UrsaCraft_video.py
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/Grass_block.blend
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/Sans.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm.blend
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm.blend1
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm.mtl
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm.obj
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm_texture.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/arm_texture.psd
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/block.mtl
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/block.obj
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/block_textures.psd
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/brick_block.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/dirt_block.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/grass_block.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/punch.xmp
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/punch_sound.wav
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/skybox.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/assets/stone_block.png
  Minecraft-in-Python-main/Minecraft-in-Python-main/ursina_intro.py
Labels: Hacktoberfest-Accepted, Game, Hacktoberfest

#16 Create lottery_system_game.py
  Python codes/lottery_system_game.py
Labels: Hacktoberfest-Accepted, Hacktoberfest

#18 Create calculator.py
  Python codes/calculator.py
Labels: Hacktoberfest-Accepted, Hacktoberfest

#21 added sudoku solver code in java
  Java Codes/SudokuSolver.java
Labels: Hacktoberfest-Accepted, Hacktoberfest

#26 added josephus problem
  Java Codes/josephusproblem.java
Labels: Hacktoberfest-Accepted, Hacktoberfest

#25 Add Tic Tac Toe game in python
  Python codes/Tic_Tac_toe.py
Labels: Hacktoberfest-Accepted, Hacktoberfest

#37 added DFS code in java
  Java Codes/DepthFirstSearch.java
Labels: Hacktoberfest-Accepted, Hacktoberfest

#36 Added Two Code Files
  Python codes/armstrong_number.py
  Python codes/pattern.py
Labels: Hacktoberfest-Accepted, Hacktoberfest

#38 added code for BFS algorithm in java
  Java Codes/BreadthFirstSearch.java
Labels: Hacktoberfest-Accepted, Hacktoberfest

#39 c++ sorting algorithms added
  c++/RadixSort.cpp
  c++/Selection.cpp
  c++/binOrbucketSort.cpp
  c++/bubble_Sort.cpp
  c++/insertion_sort.cpp
  c++/mergeSortSir.cpp
  c++/quickSort.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest, DSA

#42 Added Shell Sort Code
  c++/ShellSort.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest, DSA

#45 Added Java Code
  Java Codes/HeapSort.java
Labels: Hacktoberfest-Accepted, Hacktoberfest, DSA

#46 added-Js
  JavaScript/Calculator/index.html
  JavaScript/Calculator/logic.js
  JavaScript/Calculator/style.css
Labels: Hacktoberfest-Accepted, Hacktoberfest
